//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySach_B3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Book
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Tiêu đề không được để trống")]
        [StringLength(50, ErrorMessage = "Tiêu đề kí tự không quá 100 kí tự!")]
        public string Title { get; set; }
        [Required(ErrorMessage = "Nội dung không được để trống")]
        public string Description { get; set; }
        [Required(ErrorMessage = "Tên tác giả không được để trống")]
        [StringLength(50, ErrorMessage = "Tên tác giả kí tự không quá 30 kí tự!")]
        public string Author { get; set; }
        [Required(ErrorMessage = "Hình ảnh không được để trống")]
        public string ImageCover { get; set; }
        [Required(ErrorMessage = "Giá không được để trống")]
        [Range(minimum: 1000, maximum: 1000000, ErrorMessage = "Giá phải từ 1000-1000000")]
        public double Price { get; set; }
    }
}
